上传了自己写的一个插件
sealdice/javascript pull request #45
Opened 2024-09-19 23:34 UTC by cherrybird7

插件是辅助使用腾讯的官方机器人的

2024-10-11 17:25 UTC, Szzrain requested changes
不要上传压缩包

2024-10-12 12:24 UTC, cherrybird7 commented
> 不要上传压缩包

上传了个不是压缩包形式的

2024-10-17 19:39 UTC, Szzrain commented
> > 不要上传压缩包
> 
> 上传了个不是压缩包形式的

压缩包依然存在于 changes 中，请将其从提交中移除

2024-10-21 05:53 UTC, cherrybird7 commented
已把压缩包删除

> > > 不要上传压缩包
> > 
> > 
> > 上传了个不是压缩包形式的
> 
> 压缩包依然存在于 changes 中，请将其从提交中移除

2024-10-30 02:29 UTC, Szzrain approved these changes

2024-10-30 02:29 UTC, merged